//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.237
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Runtime.Serialization.ContractNamespaceAttribute("UFSoft.UBF.Exceptions", ClrNamespace = "UFSoft.UBF.Exceptions1")]
[assembly: System.Runtime.Serialization.ContractNamespaceAttribute("UFSoft.UBF.Util.Data", ClrNamespace = "UFSoft.UBF.Util.Data")]
[assembly: System.Runtime.Serialization.ContractNamespaceAttribute("http://www.UFIDA.org/EntityData", ClrNamespace = "www.ufida.org.EntityData")]

namespace UFSoft.UBF
{
    using System;
    using System.Runtime.Serialization;


    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UFSoft.UBF.UnknownException))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UFSoft.UBF.Business.BusinessException))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UFSoft.UBF.Business.AttrsContainerException))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UFSoft.UBF.Business.AttributeInValidException))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UFSoft.UBF.Business.EntityNotExistException))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UFSoft.UBF.Service.ServiceLostException))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UFSoft.UBF.Service.ServiceException))]
    public partial class ExceptionBase : System.Exception
    {

        public ExceptionBase(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context) :
            base(info, context)
        {
        }

        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name = "ExceptionBase.FormatState", Namespace = "http://schemas.datacontract.org/2004/07/UFSoft.UBF")]
        public enum FormatState : uint
        {

            [System.Runtime.Serialization.EnumMemberAttribute()]
            None = 0,

            [System.Runtime.Serialization.EnumMemberAttribute()]
            Formatting = 1,

            [System.Runtime.Serialization.EnumMemberAttribute()]
            Formatted = 2,
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.SerializableAttribute()]
    public partial class UnknownException : UFSoft.UBF.ExceptionBase
    {

        public UnknownException(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context) :
            base(info, context)
        {
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "ErrorMessage", Namespace = "http://schemas.datacontract.org/2004/07/UFSoft.UBF")]
    public partial class ErrorMessage : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private UFSoft.UBF.ErrorDescriptor errDescriptorField;

        private string errorTypeField;

        private UFSoft.UBF.ErrorMessage[] innerMessagesField;

        private string messageField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        public UFSoft.UBF.ErrorDescriptor errDescriptor
        {
            get
            {
                return this.errDescriptorField;
            }
            set
            {
                this.errDescriptorField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        public string errorType
        {
            get
            {
                return this.errorTypeField;
            }
            set
            {
                this.errorTypeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public UFSoft.UBF.ErrorMessage[] innerMessages
        {
            get
            {
                return this.innerMessagesField;
            }
            set
            {
                this.innerMessagesField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "ErrorDescriptor", Namespace = "http://schemas.datacontract.org/2004/07/UFSoft.UBF")]
    public partial class ErrorDescriptor : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private string categoryField;

        private string erroridField;

        private UFSoft.UBF.ErrorLevel levelField;

        private string ownerField;

        private System.DateTime timeStampField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string category
        {
            get
            {
                return this.categoryField;
            }
            set
            {
                this.categoryField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        public string errorid
        {
            get
            {
                return this.erroridField;
            }
            set
            {
                this.erroridField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public UFSoft.UBF.ErrorLevel level
        {
            get
            {
                return this.levelField;
            }
            set
            {
                this.levelField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string owner
        {
            get
            {
                return this.ownerField;
            }
            set
            {
                this.ownerField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime timeStamp
        {
            get
            {
                return this.timeStampField;
            }
            set
            {
                this.timeStampField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "ErrorLevel", Namespace = "http://schemas.datacontract.org/2004/07/UFSoft.UBF")]
    public enum ErrorLevel : short
    {

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Debug = 0,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Info = 1,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Warn = 2,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Error = 3,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Fatal = 4,
    }
}
namespace UFSoft.UBF.Business
{
    using System;
    using System.Runtime.Serialization;


    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UFSoft.UBF.Business.AttrsContainerException))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UFSoft.UBF.Business.AttributeInValidException))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UFSoft.UBF.Business.EntityNotExistException))]
    public partial class BusinessException : UFSoft.UBF.ExceptionBase
    {

        public BusinessException(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context) :
            base(info, context)
        {
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.SerializableAttribute()]
    public partial class AttrsContainerException : UFSoft.UBF.Business.BusinessException
    {

        public AttrsContainerException(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context) :
            base(info, context)
        {
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.SerializableAttribute()]
    public partial class AttributeInValidException : UFSoft.UBF.Business.BusinessException
    {

        public AttributeInValidException(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context) :
            base(info, context)
        {
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.SerializableAttribute()]
    public partial class EntityNotExistException : UFSoft.UBF.Business.BusinessException
    {

        public EntityNotExistException(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context) :
            base(info, context)
        {
        }
    }
}
namespace UFSoft.UBF.Service
{
    using System;
    using System.Runtime.Serialization;


    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.SerializableAttribute()]
    public partial class ServiceLostException : UFSoft.UBF.ExceptionBase
    {

        public ServiceLostException(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context) :
            base(info, context)
        {
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.SerializableAttribute()]
    public partial class ServiceException : UFSoft.UBF.ExceptionBase
    {

        public ServiceException(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context) :
            base(info, context)
        {
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "ServiceExceptionDetail", Namespace = "http://schemas.datacontract.org/2004/07/UFSoft.UBF.Service")]
    public partial class ServiceExceptionDetail : System.ServiceModel.ExceptionDetail, System.Runtime.Serialization.IExtensibleDataObject
    {
        public ServiceExceptionDetail(Exception exception) : base(exception) { }
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private UFSoft.UBF.ExceptionBase ExceptionField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public UFSoft.UBF.ExceptionBase Exception
        {
            get
            {
                return this.ExceptionField;
            }
            set
            {
                this.ExceptionField = value;
            }
        }
    }
}
namespace UFSoft.UBF.Util.Context
{
    using System.Runtime.Serialization;


    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "ApplicationContext", Namespace = "http://schemas.datacontract.org/2004/07/UFSoft.UBF.Util.Context")]
    public partial class ApplicationContext : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private System.Collections.Generic.Dictionary<object, object> nameValueHasField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        public System.Collections.Generic.Dictionary<object, object> nameValueHas
        {
            get
            {
                return this.nameValueHasField;
            }
            set
            {
                this.nameValueHasField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "PlatformContext", Namespace = "http://schemas.datacontract.org/2004/07/UFSoft.UBF.Util.Context")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Exception))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Exception[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UFSoft.UBF.ExceptionBase))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UFSoft.UBF.UnknownException))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UFSoft.UBF.ErrorMessage))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UFSoft.UBF.ErrorDescriptor))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UFSoft.UBF.ErrorLevel))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UFSoft.UBF.ErrorMessage[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UFSoft.UBF.ExceptionBase.FormatState))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UFSoft.UBF.Business.BusinessException))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UFSoft.UBF.Business.AttrsContainerException))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UFSoft.UBF.Business.AttributeInValidException))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UFSoft.UBF.Business.EntityNotExistException))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UFSoft.UBF.Util.Context.ApplicationContext))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UFSoft.UBF.Util.Context.ThreadContext))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<object, object>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UFSoft.UBF.Exceptions.MessageBaseFormatState))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UFSoft.UBF.Exceptions1.MessageBase))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UFSoft.UBF.Exceptions1.MessageBase[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UFSoft.UBF.Util.Data.MultiLangDataDict))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UFSoft.UBF.Util.Data.MultiLangData[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UFSoft.UBF.Util.Data.MultiLangData))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(www.ufida.org.EntityData.UFIDAU9CustJSDYBarCodeCheckBarCodeDTOData[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(www.ufida.org.EntityData.UFIDAU9CustJSDYBarCodeCheckBarCodeDTOData))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(www.ufida.org.EntityData.UFIDAU9CustJSDYBarCodeProductBarCodeByShipDTOData[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(www.ufida.org.EntityData.UFIDAU9CustJSDYBarCodeProductBarCodeByShipDTOData))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(www.ufida.org.EntityData.UFIDAU9CustJSDYBarCodeProductBarCodeByCompleteApplyDTOData[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(www.ufida.org.EntityData.UFIDAU9CustJSDYBarCodeProductBarCodeByCompleteApplyDTOData))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(www.ufida.org.EntityData.UFSoftUBFBusinessDataTransObjectBase))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.ServiceModel.ExceptionDetail))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UFSoft.UBF.PL.Engine.ObjectState))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Data.DataRowState))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UFSoft.UBF.Service.ServiceLostException))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UFSoft.UBF.Service.ServiceException))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UFSoft.UBF.Service.ServiceExceptionDetail))]
    public partial class PlatformContext : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private object ctxField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        public object ctx
        {
            get
            {
                return this.ctxField;
            }
            set
            {
                this.ctxField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "ThreadContext", Namespace = "http://schemas.datacontract.org/2004/07/UFSoft.UBF.Util.Context")]
    public partial class ThreadContext : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private System.Collections.Generic.Dictionary<object, object> nameValueHasField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        public System.Collections.Generic.Dictionary<object, object> nameValueHas
        {
            get
            {
                return this.nameValueHasField;
            }
            set
            {
                this.nameValueHasField = value;
            }
        }
    }
}
namespace UFSoft.UBF.Exceptions
{
    using System.Runtime.Serialization;


    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "MessageBase.FormatState", Namespace = "http://schemas.datacontract.org/2004/07/UFSoft.UBF.Exceptions")]
    public enum MessageBaseFormatState : uint
    {

        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 0,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Formatting = 1,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Formatted = 2,
    }
}
namespace UFSoft.UBF.Exceptions1
{
    using System.Runtime.Serialization;


    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "MessageBase", Namespace = "UFSoft.UBF.Exceptions")]
    public partial class MessageBase : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private string attributeMetadataIDField;

        private string attributeNameField;

        private string entityFullNameField;

        private long entityIDField;

        private string entityMetadataIDField;

        private short errorLevelField;

        private UFSoft.UBF.Exceptions.MessageBaseFormatState formatedField;

        private UFSoft.UBF.Exceptions1.MessageBase[] innerMessagesField;

        private bool isValidEntityIDField;

        private string localMessageField;

        private string orginalEntityFullNameField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string attributeMetadataID
        {
            get
            {
                return this.attributeMetadataIDField;
            }
            set
            {
                this.attributeMetadataIDField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string attributeName
        {
            get
            {
                return this.attributeNameField;
            }
            set
            {
                this.attributeNameField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string entityFullName
        {
            get
            {
                return this.entityFullNameField;
            }
            set
            {
                this.entityFullNameField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public long entityID
        {
            get
            {
                return this.entityIDField;
            }
            set
            {
                this.entityIDField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string entityMetadataID
        {
            get
            {
                return this.entityMetadataIDField;
            }
            set
            {
                this.entityMetadataIDField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public short errorLevel
        {
            get
            {
                return this.errorLevelField;
            }
            set
            {
                this.errorLevelField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public UFSoft.UBF.Exceptions.MessageBaseFormatState formated
        {
            get
            {
                return this.formatedField;
            }
            set
            {
                this.formatedField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public UFSoft.UBF.Exceptions1.MessageBase[] innerMessages
        {
            get
            {
                return this.innerMessagesField;
            }
            set
            {
                this.innerMessagesField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool isValidEntityID
        {
            get
            {
                return this.isValidEntityIDField;
            }
            set
            {
                this.isValidEntityIDField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string localMessage
        {
            get
            {
                return this.localMessageField;
            }
            set
            {
                this.localMessageField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string orginalEntityFullName
        {
            get
            {
                return this.orginalEntityFullNameField;
            }
            set
            {
                this.orginalEntityFullNameField = value;
            }
        }
    }
}
namespace UFSoft.UBF.Util.Data
{
    using System.Runtime.Serialization;


    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "MultiLangDataDict", Namespace = "UFSoft.UBF.Util.Data")]
    public partial class MultiLangDataDict : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private UFSoft.UBF.Util.Data.MultiLangData[] _langsField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public UFSoft.UBF.Util.Data.MultiLangData[] _langs
        {
            get
            {
                return this._langsField;
            }
            set
            {
                this._langsField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "MultiLangData", Namespace = "UFSoft.UBF.Util.Data")]
    public partial class MultiLangData : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private string LangTypeField;

        private string LangValueField;

        private System.Data.DataRowState StateField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LangType
        {
            get
            {
                return this.LangTypeField;
            }
            set
            {
                this.LangTypeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LangValue
        {
            get
            {
                return this.LangValueField;
            }
            set
            {
                this.LangValueField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Data.DataRowState State
        {
            get
            {
                return this.StateField;
            }
            set
            {
                this.StateField = value;
            }
        }
    }
}
namespace www.ufida.org.EntityData
{
    using System.Runtime.Serialization;


    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "UFIDA.U9.Cust.JSDY.BarCode.ProductBarCodeByShipDTOData", Namespace = "http://www.UFIDA.org/EntityData", IsReference = true)]
    public partial class UFIDAU9CustJSDYBarCodeProductBarCodeByShipDTOData : www.ufida.org.EntityData.UFSoftUBFBusinessDataTransObjectBase
    {

        private int m_actualLengthField;

        private string m_barCodeField;

        private long m_itemIDField;

        private long m_orgIDField;

        private long m_qcOperatorField;

        private string m_scanByField;

        private System.DateTime m_scanOnField;

        private long m_shipPlanField;

        private long m_shipPlanLineField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int m_actualLength
        {
            get
            {
                return this.m_actualLengthField;
            }
            set
            {
                this.m_actualLengthField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string m_barCode
        {
            get
            {
                return this.m_barCodeField;
            }
            set
            {
                this.m_barCodeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public long m_itemID
        {
            get
            {
                return this.m_itemIDField;
            }
            set
            {
                this.m_itemIDField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public long m_orgID
        {
            get
            {
                return this.m_orgIDField;
            }
            set
            {
                this.m_orgIDField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public long m_qcOperator
        {
            get
            {
                return this.m_qcOperatorField;
            }
            set
            {
                this.m_qcOperatorField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string m_scanBy
        {
            get
            {
                return this.m_scanByField;
            }
            set
            {
                this.m_scanByField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime m_scanOn
        {
            get
            {
                return this.m_scanOnField;
            }
            set
            {
                this.m_scanOnField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public long m_shipPlan
        {
            get
            {
                return this.m_shipPlanField;
            }
            set
            {
                this.m_shipPlanField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public long m_shipPlanLine
        {
            get
            {
                return this.m_shipPlanLineField;
            }
            set
            {
                this.m_shipPlanLineField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "UFIDA.U9.Cust.JSDY.BarCode.ProductBarCodeByCompleteApplyDTOData", Namespace = "http://www.UFIDA.org/EntityData", IsReference = true)]
    public partial class UFIDAU9CustJSDYBarCodeProductBarCodeByCompleteApplyDTOData : www.ufida.org.EntityData.UFSoftUBFBusinessDataTransObjectBase
    {

        private int m_actualLengthField;

        private string m_barCodeField;

        private long m_completeApplyDocField;

        private long m_completeApplyDocLineField;

        private long m_itemIDField;

        private long m_orgIDField;

        private long m_qcOperatorField;

        private string m_scanByField;

        private System.DateTime m_scanOnField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int m_actualLength
        {
            get
            {
                return this.m_actualLengthField;
            }
            set
            {
                this.m_actualLengthField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string m_barCode
        {
            get
            {
                return this.m_barCodeField;
            }
            set
            {
                this.m_barCodeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public long m_completeApplyDoc
        {
            get
            {
                return this.m_completeApplyDocField;
            }
            set
            {
                this.m_completeApplyDocField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public long m_completeApplyDocLine
        {
            get
            {
                return this.m_completeApplyDocLineField;
            }
            set
            {
                this.m_completeApplyDocLineField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public long m_itemID
        {
            get
            {
                return this.m_itemIDField;
            }
            set
            {
                this.m_itemIDField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public long m_orgID
        {
            get
            {
                return this.m_orgIDField;
            }
            set
            {
                this.m_orgIDField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public long m_qcOperator
        {
            get
            {
                return this.m_qcOperatorField;
            }
            set
            {
                this.m_qcOperatorField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string m_scanBy
        {
            get
            {
                return this.m_scanByField;
            }
            set
            {
                this.m_scanByField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime m_scanOn
        {
            get
            {
                return this.m_scanOnField;
            }
            set
            {
                this.m_scanOnField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "UFIDA.U9.Cust.JSDY.BarCode.CheckBarCodeDTOData", Namespace = "http://www.UFIDA.org/EntityData", IsReference = true)]
    public partial class UFIDAU9CustJSDYBarCodeCheckBarCodeDTOData : www.ufida.org.EntityData.UFSoftUBFBusinessDataTransObjectBase
    {

        private int m_actualLengthField;

        private string m_barCodeField;

        private string m_checkedByField;

        private System.DateTime m_checkedOnField;

        private long m_itemIDField;

        private long m_orgIDField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int m_actualLength
        {
            get
            {
                return this.m_actualLengthField;
            }
            set
            {
                this.m_actualLengthField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string m_barCode
        {
            get
            {
                return this.m_barCodeField;
            }
            set
            {
                this.m_barCodeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string m_checkedBy
        {
            get
            {
                return this.m_checkedByField;
            }
            set
            {
                this.m_checkedByField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime m_checkedOn
        {
            get
            {
                return this.m_checkedOnField;
            }
            set
            {
                this.m_checkedOnField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public long m_itemID
        {
            get
            {
                return this.m_itemIDField;
            }
            set
            {
                this.m_itemIDField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public long m_orgID
        {
            get
            {
                return this.m_orgIDField;
            }
            set
            {
                this.m_orgIDField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "UFSoft.UBF.Business.DataTransObjectBase", Namespace = "http://www.UFIDA.org/EntityData", IsReference = true)]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(www.ufida.org.EntityData.UFIDAU9CustJSDYBarCodeCheckBarCodeDTOData))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(www.ufida.org.EntityData.UFIDAU9CustJSDYBarCodeProductBarCodeByCompleteApplyDTOData))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(www.ufida.org.EntityData.UFIDAU9CustJSDYBarCodeProductBarCodeByShipDTOData))]
    public partial class UFSoftUBFBusinessDataTransObjectBase : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private UFSoft.UBF.PL.Engine.ObjectState sysStateField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public UFSoft.UBF.PL.Engine.ObjectState sysState
        {
            get
            {
                return this.sysStateField;
            }
            set
            {
                this.sysStateField = value;
            }
        }
    }
}
namespace UFSoft.UBF.PL.Engine
{
    using System.Runtime.Serialization;


    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "ObjectState", Namespace = "http://schemas.datacontract.org/2004/07/UFSoft.UBF.PL.Engine")]
    public enum ObjectState : int
    {

        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotExist = -1,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unchanged = 1,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unknown = 0,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Inserted = 2,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Updated = 4,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Deleted = 8,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Operating = 9,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        NeedLoad = 10,
    }
}
namespace System.Data
{
    using System;
    using System.Runtime.Serialization;


    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.FlagsAttribute()]
    [System.Runtime.Serialization.DataContractAttribute(Name = "DataRowState", Namespace = "http://schemas.datacontract.org/2004/07/System.Data")]
    public enum DataRowState : int
    {

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Detached = 1,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unchanged = 2,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Added = 4,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Deleted = 8,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Modified = 16,
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Name = "UFIDA.U9.Cust.JSDY.BarCode.IGenCheckBarCodes", Namespace = "http://www.UFIDA.org", ConfigurationName = "UFIDAU9CustJSDYBarCodeIGenCheckBarCodes")]
public interface UFIDAU9CustJSDYBarCodeIGenCheckBarCodes
{

    [System.ServiceModel.OperationContractAttribute(Action = "http://www.UFIDA.org/UFIDA.U9.Cust.JSDY.BarCode.IGenCheckBarCodes/Do", ReplyAction = "http://www.UFIDA.org/UFIDA.U9.Cust.JSDY.BarCode.IGenCheckBarCodes/DoResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(UFSoft.UBF.Service.ServiceLostException), Action = "http://www.UFIDA.org/UFIDA.U9.Cust.JSDY.BarCode.IGenCheckBarCodes/DoServiceLostEx" +
        "ceptionFault", Name = "ServiceLostException", Namespace = "http://schemas.datacontract.org/2004/07/UFSoft.UBF.Service")]
    [System.ServiceModel.FaultContractAttribute(typeof(UFSoft.UBF.Service.ServiceException), Action = "http://www.UFIDA.org/UFIDA.U9.Cust.JSDY.BarCode.IGenCheckBarCodes/DoServiceExcept" +
        "ionFault", Name = "ServiceException", Namespace = "http://schemas.datacontract.org/2004/07/UFSoft.UBF.Service")]
    [System.ServiceModel.FaultContractAttribute(typeof(UFSoft.UBF.Service.ServiceExceptionDetail), Action = "http://www.UFIDA.org/UFIDA.U9.Cust.JSDY.BarCode.IGenCheckBarCodes/DoServiceExcept" +
        "ionDetailFault", Name = "ServiceExceptionDetail", Namespace = "http://schemas.datacontract.org/2004/07/UFSoft.UBF.Service")]
    [System.ServiceModel.FaultContractAttribute(typeof(UFSoft.UBF.ExceptionBase), Action = "http://www.UFIDA.org/UFIDA.U9.Cust.JSDY.BarCode.IGenCheckBarCodes/DoExceptionBase" +
        "Fault", Name = "ExceptionBase", Namespace = "http://schemas.datacontract.org/2004/07/UFSoft.UBF")]
    [System.ServiceModel.FaultContractAttribute(typeof(System.Exception), Action = "http://www.UFIDA.org/UFIDA.U9.Cust.JSDY.BarCode.IGenCheckBarCodes/DoExceptionFaul" +
        "t", Name = "Exception", Namespace = "http://schemas.datacontract.org/2004/07/System")]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Exception))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Exception[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UFSoft.UBF.ExceptionBase))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UFSoft.UBF.UnknownException))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UFSoft.UBF.ErrorMessage))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UFSoft.UBF.ErrorDescriptor))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UFSoft.UBF.ErrorLevel))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UFSoft.UBF.ErrorMessage[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UFSoft.UBF.ExceptionBase.FormatState))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UFSoft.UBF.Business.BusinessException))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UFSoft.UBF.Business.AttrsContainerException))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UFSoft.UBF.Business.AttributeInValidException))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UFSoft.UBF.Business.EntityNotExistException))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UFSoft.UBF.Util.Context.ApplicationContext))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UFSoft.UBF.Util.Context.PlatformContext))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UFSoft.UBF.Util.Context.ThreadContext))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<object, object>))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UFSoft.UBF.Exceptions.MessageBaseFormatState))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UFSoft.UBF.Exceptions1.MessageBase))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UFSoft.UBF.Exceptions1.MessageBase[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UFSoft.UBF.Util.Data.MultiLangDataDict))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UFSoft.UBF.Util.Data.MultiLangData[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UFSoft.UBF.Util.Data.MultiLangData))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(www.ufida.org.EntityData.UFIDAU9CustJSDYBarCodeCheckBarCodeDTOData[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(www.ufida.org.EntityData.UFIDAU9CustJSDYBarCodeCheckBarCodeDTOData))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(www.ufida.org.EntityData.UFSoftUBFBusinessDataTransObjectBase))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.ServiceModel.ExceptionDetail))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UFSoft.UBF.PL.Engine.ObjectState))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Data.DataRowState))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UFSoft.UBF.Service.ServiceLostException))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UFSoft.UBF.Service.ServiceException))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UFSoft.UBF.Service.ServiceExceptionDetail))]
    [return: System.ServiceModel.MessageParameterAttribute(Name = "outMessages")]
    UFSoft.UBF.Exceptions1.MessageBase[] Do(object context, www.ufida.org.EntityData.UFIDAU9CustJSDYBarCodeCheckBarCodeDTOData[] checkBarCodeDTOs);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface UFIDAU9CustJSDYBarCodeIGenCheckBarCodesChannel : UFIDAU9CustJSDYBarCodeIGenCheckBarCodes, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class UFIDAU9CustJSDYBarCodeIGenCheckBarCodesClient : System.ServiceModel.ClientBase<UFIDAU9CustJSDYBarCodeIGenCheckBarCodes>, UFIDAU9CustJSDYBarCodeIGenCheckBarCodes
{

    public UFIDAU9CustJSDYBarCodeIGenCheckBarCodesClient()
    {
    }

    public UFIDAU9CustJSDYBarCodeIGenCheckBarCodesClient(string endpointConfigurationName) :
        base(endpointConfigurationName)
    {
    }

    public UFIDAU9CustJSDYBarCodeIGenCheckBarCodesClient(string endpointConfigurationName, string remoteAddress) :
        base(endpointConfigurationName, remoteAddress)
    {
    }

    public UFIDAU9CustJSDYBarCodeIGenCheckBarCodesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
        base(endpointConfigurationName, remoteAddress)
    {
    }

    public UFIDAU9CustJSDYBarCodeIGenCheckBarCodesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
        base(binding, remoteAddress)
    {
    }

    public UFSoft.UBF.Exceptions1.MessageBase[] Do(object context, www.ufida.org.EntityData.UFIDAU9CustJSDYBarCodeCheckBarCodeDTOData[] checkBarCodeDTOs)
    {
        return base.Channel.Do(context, checkBarCodeDTOs);
    }
}



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Name = "UFIDA.U9.Cust.JSDY.BarCode.IGenProductBarCodesByCompleteApply", Namespace = "http://www.UFIDA.org", ConfigurationName = "UFIDAU9CustJSDYBarCodeIGenProductBarCodesByCompleteApply")]
public interface UFIDAU9CustJSDYBarCodeIGenProductBarCodesByCompleteApply
{

    [System.ServiceModel.OperationContractAttribute(Action = "http://www.UFIDA.org/UFIDA.U9.Cust.JSDY.BarCode.IGenProductBarCodesByCompleteAppl" +
        "y/Do", ReplyAction = "http://www.UFIDA.org/UFIDA.U9.Cust.JSDY.BarCode.IGenProductBarCodesByCompleteAppl" +
        "y/DoResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(UFSoft.UBF.Service.ServiceLostException), Action = "http://www.UFIDA.org/UFIDA.U9.Cust.JSDY.BarCode.IGenProductBarCodesByCompleteAppl" +
        "y/DoServiceLostExceptionFault", Name = "ServiceLostException", Namespace = "http://schemas.datacontract.org/2004/07/UFSoft.UBF.Service")]
    [System.ServiceModel.FaultContractAttribute(typeof(UFSoft.UBF.Service.ServiceException), Action = "http://www.UFIDA.org/UFIDA.U9.Cust.JSDY.BarCode.IGenProductBarCodesByCompleteAppl" +
        "y/DoServiceExceptionFault", Name = "ServiceException", Namespace = "http://schemas.datacontract.org/2004/07/UFSoft.UBF.Service")]
    [System.ServiceModel.FaultContractAttribute(typeof(UFSoft.UBF.Service.ServiceExceptionDetail), Action = "http://www.UFIDA.org/UFIDA.U9.Cust.JSDY.BarCode.IGenProductBarCodesByCompleteAppl" +
        "y/DoServiceExceptionDetailFault", Name = "ServiceExceptionDetail", Namespace = "http://schemas.datacontract.org/2004/07/UFSoft.UBF.Service")]
    [System.ServiceModel.FaultContractAttribute(typeof(UFSoft.UBF.ExceptionBase), Action = "http://www.UFIDA.org/UFIDA.U9.Cust.JSDY.BarCode.IGenProductBarCodesByCompleteAppl" +
        "y/DoExceptionBaseFault", Name = "ExceptionBase", Namespace = "http://schemas.datacontract.org/2004/07/UFSoft.UBF")]
    [System.ServiceModel.FaultContractAttribute(typeof(System.Exception), Action = "http://www.UFIDA.org/UFIDA.U9.Cust.JSDY.BarCode.IGenProductBarCodesByCompleteAppl" +
        "y/DoExceptionFault", Name = "Exception", Namespace = "http://schemas.datacontract.org/2004/07/System")]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UFSoft.UBF.ExceptionBase))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UFSoft.UBF.UnknownException))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UFSoft.UBF.ErrorMessage))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UFSoft.UBF.ErrorDescriptor))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UFSoft.UBF.ErrorLevel))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UFSoft.UBF.ErrorMessage[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UFSoft.UBF.ExceptionBase.FormatState))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.ServiceModel.ExceptionDetail))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UFSoft.UBF.Service.ServiceLostException))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UFSoft.UBF.Service.ServiceException))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UFSoft.UBF.Service.ServiceExceptionDetail))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UFSoft.UBF.Exceptions.MessageBaseFormatState))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UFSoft.UBF.Business.BusinessException))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UFSoft.UBF.Business.AttrsContainerException))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UFSoft.UBF.Business.AttributeInValidException))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UFSoft.UBF.Business.EntityNotExistException))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UFSoft.UBF.Util.Data.MultiLangDataDict))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UFSoft.UBF.Util.Data.MultiLangData[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UFSoft.UBF.Util.Data.MultiLangData))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<object, object>))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UFSoft.UBF.Exceptions1.MessageBase))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UFSoft.UBF.Exceptions1.MessageBase[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Data.DataRowState))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(www.ufida.org.EntityData.UFIDAU9CustJSDYBarCodeProductBarCodeByCompleteApplyDTOData[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(www.ufida.org.EntityData.UFIDAU9CustJSDYBarCodeProductBarCodeByCompleteApplyDTOData))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(www.ufida.org.EntityData.UFSoftUBFBusinessDataTransObjectBase))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UFSoft.UBF.Util.Context.ApplicationContext))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UFSoft.UBF.Util.Context.PlatformContext))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UFSoft.UBF.Util.Context.ThreadContext))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Exception))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Exception[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UFSoft.UBF.PL.Engine.ObjectState))]
    [return: System.ServiceModel.MessageParameterAttribute(Name = "outMessages")]
    UFSoft.UBF.Exceptions1.MessageBase[] Do(object context, www.ufida.org.EntityData.UFIDAU9CustJSDYBarCodeProductBarCodeByCompleteApplyDTOData[] productBarCodeDTOs);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface UFIDAU9CustJSDYBarCodeIGenProductBarCodesByCompleteApplyChannel : UFIDAU9CustJSDYBarCodeIGenProductBarCodesByCompleteApply, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class UFIDAU9CustJSDYBarCodeIGenProductBarCodesByCompleteApplyClient : System.ServiceModel.ClientBase<UFIDAU9CustJSDYBarCodeIGenProductBarCodesByCompleteApply>, UFIDAU9CustJSDYBarCodeIGenProductBarCodesByCompleteApply
{

    public UFIDAU9CustJSDYBarCodeIGenProductBarCodesByCompleteApplyClient()
    {
    }

    public UFIDAU9CustJSDYBarCodeIGenProductBarCodesByCompleteApplyClient(string endpointConfigurationName) :
        base(endpointConfigurationName)
    {
    }

    public UFIDAU9CustJSDYBarCodeIGenProductBarCodesByCompleteApplyClient(string endpointConfigurationName, string remoteAddress) :
        base(endpointConfigurationName, remoteAddress)
    {
    }

    public UFIDAU9CustJSDYBarCodeIGenProductBarCodesByCompleteApplyClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
        base(endpointConfigurationName, remoteAddress)
    {
    }

    public UFIDAU9CustJSDYBarCodeIGenProductBarCodesByCompleteApplyClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
        base(binding, remoteAddress)
    {
    }

    public UFSoft.UBF.Exceptions1.MessageBase[] Do(object context, www.ufida.org.EntityData.UFIDAU9CustJSDYBarCodeProductBarCodeByCompleteApplyDTOData[] productBarCodeDTOs)
    {
        return base.Channel.Do(context, productBarCodeDTOs);
    }
}



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Name = "UFIDA.U9.Cust.JSDY.BarCode.IGenProductBarCodesByShip", Namespace = "http://www.UFIDA.org", ConfigurationName = "UFIDAU9CustJSDYBarCodeIGenProductBarCodesByShip")]
public interface UFIDAU9CustJSDYBarCodeIGenProductBarCodesByShip
{

    [System.ServiceModel.OperationContractAttribute(Action = "http://www.UFIDA.org/UFIDA.U9.Cust.JSDY.BarCode.IGenProductBarCodesByShip/Do", ReplyAction = "http://www.UFIDA.org/UFIDA.U9.Cust.JSDY.BarCode.IGenProductBarCodesByShip/DoRespo" +
        "nse")]
    [System.ServiceModel.FaultContractAttribute(typeof(UFSoft.UBF.Service.ServiceLostException), Action = "http://www.UFIDA.org/UFIDA.U9.Cust.JSDY.BarCode.IGenProductBarCodesByShip/DoServi" +
        "ceLostExceptionFault", Name = "ServiceLostException", Namespace = "http://schemas.datacontract.org/2004/07/UFSoft.UBF.Service")]
    [System.ServiceModel.FaultContractAttribute(typeof(UFSoft.UBF.Service.ServiceException), Action = "http://www.UFIDA.org/UFIDA.U9.Cust.JSDY.BarCode.IGenProductBarCodesByShip/DoServi" +
        "ceExceptionFault", Name = "ServiceException", Namespace = "http://schemas.datacontract.org/2004/07/UFSoft.UBF.Service")]
    [System.ServiceModel.FaultContractAttribute(typeof(UFSoft.UBF.Service.ServiceExceptionDetail), Action = "http://www.UFIDA.org/UFIDA.U9.Cust.JSDY.BarCode.IGenProductBarCodesByShip/DoServi" +
        "ceExceptionDetailFault", Name = "ServiceExceptionDetail", Namespace = "http://schemas.datacontract.org/2004/07/UFSoft.UBF.Service")]
    [System.ServiceModel.FaultContractAttribute(typeof(UFSoft.UBF.ExceptionBase), Action = "http://www.UFIDA.org/UFIDA.U9.Cust.JSDY.BarCode.IGenProductBarCodesByShip/DoExcep" +
        "tionBaseFault", Name = "ExceptionBase", Namespace = "http://schemas.datacontract.org/2004/07/UFSoft.UBF")]
    [System.ServiceModel.FaultContractAttribute(typeof(System.Exception), Action = "http://www.UFIDA.org/UFIDA.U9.Cust.JSDY.BarCode.IGenProductBarCodesByShip/DoExcep" +
        "tionFault", Name = "Exception", Namespace = "http://schemas.datacontract.org/2004/07/System")]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UFSoft.UBF.Util.Context.PlatformContext))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UFSoft.UBF.Util.Context.ThreadContext))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UFSoft.UBF.Util.Context.ApplicationContext))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UFSoft.UBF.Exceptions.MessageBaseFormatState))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UFSoft.UBF.Exceptions1.MessageBase))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UFSoft.UBF.Exceptions1.MessageBase[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<object, object>))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Exception))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Exception[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UFSoft.UBF.ExceptionBase))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UFSoft.UBF.UnknownException))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UFSoft.UBF.ErrorMessage))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UFSoft.UBF.ErrorDescriptor))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UFSoft.UBF.ErrorLevel))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UFSoft.UBF.ErrorMessage[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UFSoft.UBF.ExceptionBase.FormatState))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UFSoft.UBF.Business.BusinessException))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UFSoft.UBF.Business.AttrsContainerException))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UFSoft.UBF.Business.AttributeInValidException))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UFSoft.UBF.Business.EntityNotExistException))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Data.DataRowState))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(www.ufida.org.EntityData.UFIDAU9CustJSDYBarCodeProductBarCodeByShipDTOData[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(www.ufida.org.EntityData.UFIDAU9CustJSDYBarCodeProductBarCodeByShipDTOData))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(www.ufida.org.EntityData.UFSoftUBFBusinessDataTransObjectBase))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UFSoft.UBF.Util.Data.MultiLangDataDict))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UFSoft.UBF.Util.Data.MultiLangData[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UFSoft.UBF.Util.Data.MultiLangData))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UFSoft.UBF.PL.Engine.ObjectState))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.ServiceModel.ExceptionDetail))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UFSoft.UBF.Service.ServiceLostException))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UFSoft.UBF.Service.ServiceException))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UFSoft.UBF.Service.ServiceExceptionDetail))]
    [return: System.ServiceModel.MessageParameterAttribute(Name = "outMessages")]
    UFSoft.UBF.Exceptions1.MessageBase[] Do(object context, www.ufida.org.EntityData.UFIDAU9CustJSDYBarCodeProductBarCodeByShipDTOData[] productBarCodeDTOs);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface UFIDAU9CustJSDYBarCodeIGenProductBarCodesByShipChannel : UFIDAU9CustJSDYBarCodeIGenProductBarCodesByShip, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class UFIDAU9CustJSDYBarCodeIGenProductBarCodesByShipClient : System.ServiceModel.ClientBase<UFIDAU9CustJSDYBarCodeIGenProductBarCodesByShip>, UFIDAU9CustJSDYBarCodeIGenProductBarCodesByShip
{

    public UFIDAU9CustJSDYBarCodeIGenProductBarCodesByShipClient()
    {
    }

    public UFIDAU9CustJSDYBarCodeIGenProductBarCodesByShipClient(string endpointConfigurationName) :
        base(endpointConfigurationName)
    {
    }

    public UFIDAU9CustJSDYBarCodeIGenProductBarCodesByShipClient(string endpointConfigurationName, string remoteAddress) :
        base(endpointConfigurationName, remoteAddress)
    {
    }

    public UFIDAU9CustJSDYBarCodeIGenProductBarCodesByShipClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
        base(endpointConfigurationName, remoteAddress)
    {
    }

    public UFIDAU9CustJSDYBarCodeIGenProductBarCodesByShipClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
        base(binding, remoteAddress)
    {
    }

    public UFSoft.UBF.Exceptions1.MessageBase[] Do(object context, www.ufida.org.EntityData.UFIDAU9CustJSDYBarCodeProductBarCodeByShipDTOData[] productBarCodeDTOs)
    {
        return base.Channel.Do(context, productBarCodeDTOs);
    }
}
